### ISSUE TITLE
LICENSE conflicts with README

### ISSUE THREAD

**Issue by iennae** [grey-systems/chef-greysystems-mongodb#1]
Your LICENSE currently says All Rights Reserved, while your contributing information implies that contributions are welcome. Your metadata license BSD-3-Clause conflicts with the LICENSE information.

**Comment by patarra** [comment]
Hi @iennae , you're totally right, the LICENSE should say that is a BSD-3-clause.  Thanks for opening the issue, will fix it asap.

**Comment by patarra** [comment]
Hi @iennae , the license is already adjusted in release [2.0.2](https://github.com/grey-systems/chef-greysystems-mongodb/releases/tag/2.0.2).

Thanks for reporting it.
